export const INDUSTRIES = [
  'Apparel & Accessories',
  'Sportswear & Outdoor Apparel',
  'Shoes & Accessories',
  'Jewelry, Eyewear & Watches',
  'Luggage, Bags & Cases',
  'Beauty & Personal Care',
  'Health & Medical',
  'Mother, Kids & Toys',
  'Sports & Entertainment',
  'Gifts & Crafts',
  'Pet Supplies',
  'Consumer Electronics',
  'Home Appliances',
  'Electronic Components & Telecommunications',
  'Electrical Equipment & Supplies',
  'Lights & Lighting',
  'Home & Garden',
  'Furniture',
  'Construction & Real Estate',
  'Industrial Machinery',
  'Commercial Equipment & Machinery',
  'Construction & Building Machinery',
  'Tools & Hardware',
  'Material Handling',
  'Power Transmission',
  'Testing Instrument & Equipment',
  'Renewable Energy',
  'Safety & Security',
  'Chemicals',
  'Rubber & Plastics',
  'Metals & Alloys',
  'Textiles & Leather',
  'Agriculture',
  'Food & Beverage',
  'Vehicle Parts & Accessories',
  'Vehicles & Transportation',
  'Packaging & Printing',
  'School & Office Supplies',
  'Business Services',
  'Other',
];

export const CURRENCIES = ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'CNY', 'INR', 'JPY', 'Other'];

export const PLATFORMS = ['Alibaba.com', '1688.com', 'Made-in-China.com', 'Other'];
